Use parallel Needy builds
Summary:
This patch adds the flags to Needy required for parallel builds. Until Needy can disambiguate `needy satisfy -j boost` to use the correct default, we will have to manually specify the number of jobs.

OpenSSL currently does not handle parallel builds properly and so the relevant make args have not been provided.

Overall, this increases the build speed by a significant margin.

Test Plan: manual

Reviewers: mike.naquin

Reviewed By: mike.naquin

Subscribers: #engineering

Differential Revision: https://phabricator.btlive.tv/D1419

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,3 +1,16 @@
-#!/bin/sh
-./needy/scripts/needy generate jamfile
+#!/bin/bash
+
+# workaround until Needy has a way to disambiguate a blank '-j' argument
+if [[ $(uname) == 'Darwin' ]] ; then
+    NUM_CORES=$(sysctl -n hw.ncpu)
+else
+    NUM_CORES=$(nproc)
+fi
+
+./needy/scripts/needy generate jamfile --satisfy-args="-j $NUM_CORES"
+if [ ! $? ] ; then
+    echo "Configuration error."
+    exit 1
+fi
+
 echo "Configuration complete. You may now build via b2."
